name: Build Service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      working-dir:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: ${{ inputs.working-dir }}
    steps:

      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.working-dir }}/${{ inputs.service-name }} .