name: Build Service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      working-dir:
        required: true
        type: string

env:
  DOCKER_HUB_ACCESS_KEY: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}
  DOCKER_HUB_USER_NAME: ${{ secrets.DOCKER_HUB_USER_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-dir }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.working-dir }}/${{ inputs.service-name }}/ .