name: Build Service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      working-dir:
        required: true
        type: string
    secrets:
      DOCKER_HUB_ACCESS_KEY:
        required: true


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-dir }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Debug
        run: |
          echo ${{ vars.DOCKER_HUB_USER_NAME }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}

      - name: Build Docker Image
        run: |
          docker build \
          -t ${{ inputs.service-name }}:latest \ 
          ${{ inputs.working-dir }}/${{ inputs.service-name }}