name: Build Service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      working-dir:
        required: true
        type: string
      registry: 
        required: true
        type: string
      commit_hash:
        required: true
        type: string
    secrets:
      DOCKER_HUB_ACCESS_KEY:
        required: true


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-dir }}/${{ inputs.service-name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1 # docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ inputs.service-name }} Docker Image
        run: |
          docker build \
          -t ${{ inputs.registry }}/${{ inputs.service-name }}:${{ inputs.commit_hash }} \
          .

      - name: Push ${{ inputs.service-name }} Docker image
        run: |
          docker push ${{ inputs.registry }}/${{ inputs.service-name }}:${{ inputs.commit_hash }}

