name: Build Service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      working-dir:
        required: true
        type: string

env:
  DOCKER_HUB_ACCESS_KEY = ${{ secrets.DOCKER_HUB_ACCESS_KEY }}
  DOCKER_HUB_USER_NAME = ${{ secrets.DOCKER_HUB_USER_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: ${{ inputs.working-dir }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USER_NAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_KEY }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ inputs.working-dir }}/${{ inputs.service-name }} .