name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

permissions:
  id-token: write # Required for AWS OIDC connection
  contents: read  # Required for actions/checkout
  pull-requests: write # Required for GitHub bot to comment PR

env:
  SRC_CODE_DIR: ${{ vars.SRC_CODE_DIR }}
  SERVICES_NAME: "frontend"

jobs:
  build-service:
    uses: ./.github/workflows/build-service.yml
    with:
      service-name: "frontend"
      working-dir: "src"
    secrets:
      DOCKER_HUB_ACCESS_KEY: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}
# test1
#  build:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        shell: bash
#        working-directory: ${{ env.SRC_CODE_DIR }}