name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

permissions:
  id-token: write # Required for AWS OIDC connection
  contents: read  # Required for actions/checkout
  pull-requests: write # Required for GitHub bot to comment PR

env:
  SRC_CODE_DIR: ${{ vars.SRC_CODE_DIR }}
  SERVICE_NAME: "frontend"
  SERVICE_PORT: "80"
  SERVICE_CONTAINER_PORT: "8080"

jobs:
  build-and-push:
    uses: ./.github/workflows/reusable-pipelines/build-service.yml
    with:
      service-name: "frontend"
      working-dir: ${{ vars.SRC_CODE_DIR }}/frontend
      registry: ${{ vars.REGISTRY }}
      commit_hash: ${{ github.sha }}
    secrets:
      DOCKER_HUB_ACCESS_KEY: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}
   
  test:
    needs: build-and-push
    uses: ./.github/workflows/reusable-pipelines/test-service.yml
    with:
      service-name: "frontend"
      registry: ${{ vars.REGISTRY }}
      commit_hash: ${{ github.sha }}
      test_port: "80"
      container_port: "8080"
      change_tag: true

      # HTTP checks
      http_healthcheck: true
      healthcheck_path: "_healthz"
    secrets:
      DOCKER_HUB_ACCESS_KEY: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}
  
  deploy:
    needs: [ build-and-push, test ]
    uses: ./.github/workflows/reusable-pipelines/deploy-service.yml
    with:
      service-name: "frontend"
      registry: ${{ vars.REGISTRY }}
    secrets:
      DOCKER_HUB_ACCESS_KEY: ${{ secrets.DOCKER_HUB_ACCESS_KEY }}

   
# test
#  build:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        shell: bash
#        working-directory: ${{ env.SRC_CODE_DIR }}