name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

permissions:
  id-token: write # Required for AWS OIDC connection
  contents: read  # Required for actions/checkout
  pull-requests: write # Required for GitHub bot to comment PR

env:
  SRC_CODE_DIR: ${{ vars.SRC_CODE_DIR }}
  SERVICES_NAME: "frontend"

jobs:
  build-service:
    uses: ./.github/workflows/build-service.yml@main
    with:
      service-name: ${{ env.SERVICES_NAME }}
      working-dir: ${{ env.SRC_CODE_DIR }}


#  build:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        shell: bash
#        working-directory: ${{ env.SRC_CODE_DIR }}
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4      
#
#      - name: Build  ${{ env.SERVICES_NAME }}
#        uses: ./.github/actions/build-service.yml
#        with:
#          service-name: ${{ env.SERVICES_NAME }}
#          working-dir: ${{ env.SRC_CODE_DIR }}
# test