name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write # Required for AWS OIDC connection
  contents: read  # Required for actions/checkout
  pull-requests: write # Required for GitHub bot to comment PR

env:
  SRC_CODE_DIR: ${{ vars.SRC_CODE_DIR }}
  SERVICES_LIST: ${{ vars.SERVICES_LIST }}

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.SRC_CODE_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Process item
        run: |
          ls -lha
          IFS=',' read -r -a items <<< "$SERVICES_LIST"
          for item in "${items[@]}"; do
            echo "$item"
          done
