name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR

env:
  SRC_CODE_DIR: ${{ vars.SRC_CODE_DIR }}
  SERVICES_LIST: ${{ vars.SERVICES_LIST }}

jobs:

  prepare-list-of-services:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Convert ENV var to JSON
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(echo "${ITEM_LIST}" | jq -R 'split(",")')"


  build:
    needs: prepare-list-of-services
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: ${{ fromJson(needs.prepare-list-of-services.outputs.matrix) }}
    steps:
      - name: Process item
        run: echo "Processing ${{ matrix.item }}"
