name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write # Required for AWS OIDC connection
  contents: read  # Required for actions/checkout
  pull-requests: write # Required for GitHub bot to comment PR

env:
  SRC_CODE_DIR: ${{ vars.SRC_CODE_DIR }}
  SERVICES_LIST: ${{ vars.SERVICES_LIST }}

jobs:

  prepare-list-of-services:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Convert ENV var to JSON
        id: set-matrix
        run: |
          if [[ -z "${SERVICES_LIST}" ]]; then
            echo "::set-output name=matrix::[]" # Handle empty SERVICES_LIST
          else
            JSON_ARRAY=$(echo "${SERVICES_LIST}" | jq -R 'split(",")')
            echo "::set-output name=matrix::${JSON_ARRAY}" # Output JSON array
          fi

  build:
    needs: prepare-list-of-services
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: ${{ fromJson(needs.prepare-list-of-services.outputs.matrix) }}
    steps:
      - name: Process item
        run: echo "Processing ${{ matrix.item }}"
